flathub/org.kicad.KiCad

- do-not-strip-executables.patch
- org.kicad.KiCad.yml
This fixes the issue with the .Debug extension not containing debug
symbols before.
Patch by Steven A. Falco taken from Fedora package.
> Do not strip executables

- org.kicad.KiCad.yml
Prepare to move the extensions back to normal, "native" modules again, away from the `extra-data` approach.
See discussion in https://github.com/flathub/flathub/pull/2059.
> Switch extensions away from extra-data again

- org.kicad.KiCad.yml
This is meant to be merged once the new extensions:
all have been merged.
> Load other library extensions

- org.kicad.KiCad.yml
This had been changed only accidentally.
> Download boost from SourceForge again

- python3-wxPython.yml
Add verbosity during `pip install` to hopefully get a hint why #60 and #61 failed.
> Update numpy to v1.22.4

- org.kicad.KiCad.yml
Switch to git source type, so that we can use
flatpak-external-data-checker.
> Update OCCT to v7.6.2

- org.kicad.KiCad.yml
* KICAD_USE_OCE is obsolete
* KICAD_USE_OCC is active by default
So, no need to specify them anymore.
> Remove OCCT related config-opts from KiCad build

- org.kicad.KiCad.yml
The previous pattern was matching '1.80.0' in '1.80.0 beta 1',
resulting in a 404 error trying to download this yet unreleased version.
> Fix x-checker-data for boost

- org.kicad.KiCad.yml
It seems that this is no longer needed to find libngspice.
> Remove LD_LIBRARY_PATH override

- org.kicad.KiCad.yml
This allows plugins like kikit to install their dependencies without interfering with the host.
> Set PYTHONUSERBASE to a private directory

- org.kicad.KiCad.yml
- python3-requests.yml
This allows 3rd party plugins using requests to work out of the box without requiring the user to install it manually inside the flatpak.
See: https://gitlab.com/kicad/code/kicad/-/issues/12803
> Install requests Python module

- python3-requests.yml
- Update to charset_normalizer 3.1.0 (supported since requests 2.28.2)
- Keep urllib3 at 1.x.x (see https://github.com/psf/requests/issues/6432)
> Python requests dependency juggling

- org.kicad.KiCad.yml
Due to unexpected bugs
This reverts commit d44a166abd6b102977275a258bba0784d633f4c1.
> Revert "Update kicad.git to 7.0.3"

- python3-requests.yml
- python3-wxPython.yml
* Cython v0.29.35
* numpy v1.25.0
* certifi v2023.5.7
* charset_normalizer v3.1.0
* urllib3 v2.0.3
> Pre kicad 7.0.7-rc1 dependency bumps for beta

- flathub.json
- org.kicad.KiCad.yml
- python3-requests.yml
- python3-wxPython.yml
The following sources are considered important:
* kicad (main source)
* kicad-docs
* ngspice
* wxWidgets
* wxPython
* requests
"not important", i.e. only updated if at least one of the important sources above are updated, are thus:
* glu
* glew
* glm
* libXmu
* OCCT
* boost
* swig
* unixodbc
* certifi
* charset_normalizer
* idna
* urllib3
* patchelf
* openblas
* attrdict3
* packaging
* pyproject_metadata
* numpy
* Pillow
> external-data-checker: Require important updates

- flathub.json
- org.kicad.KiCad.yml
- python3-requests.yml
- python3-wxPython.yml
The following sources are considered important:
* kicad (main source)
* kicad-docs
* ngspice
* wxWidgets
* wxPython
* requests
"not important", i.e. only updated if at least one of the important sources above are updated, are thus:
* glu
* glew
* glm
* libXmu
* OCCT
* boost
* swig
* unixodbc
* certifi
* charset_normalizer
* idna
* urllib3
* patchelf
* openblas
* attrdict3
* packaging
* pyproject_metadata
* numpy
* Pillow
> Beta: external-data-checker: Require important updates

- org.kicad.KiCad.yml
- patches/0001-Avoid-crash-with-GTK3-if-console-program-is-linked-to-GUI.patch
- python3-requests.yml
See:
* https://gitlab.com/kicad/code/kicad/-/issues/15974
* https://github.com/wxWidgets/wxWidgets/issues/23981
(Also add pending dependency updates for glu and charset_normalizer)
> Fix crash reported against kicad-cli

- org.kicad.KiCad.yml
- patches/0001-Avoid-crash-with-GTK3-if-console-program-is-linked-to-GUI.patch
See:
* https://gitlab.com/kicad/code/kicad/-/issues/15974
* https://github.com/wxWidgets/wxWidgets/issues/23981
(Also add pending dependency update for glu)
> beta: Fix crash reported against kicad-cli

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-requests.yml
- python3-wxPython.yml
Update boost_1_83_0.tar.gz to 1.84.0
Update kicad.git to 7.0.10-rc1
Update OpenBLAS to v0.3.25
Update numpy-1.26.1.tar.gz to 1.26.2
Update certifi-2023.7.22-py3-none-any.whl to 2023.11.17 Update charset_normalizer-3.3.1-py3-none-any.whl to 3.3.2 Update idna-3.4-py3-none-any.whl to 3.6
Update urllib3-2.0.7-py3-none-any.whl to 2.1.0
Update kicad-doc.git to 7.0.10
> beta: KiCad 7.0.10-rc1

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-requests.yml
- python3-wxPython.yml
Update kicad-doc to v7.0.10
Update boost to v1.84.0
Update OpenBLAS to v0.3.25
Update numpy to v1.26.2
Update certifi to v2023.7.22
Update idna to v3.4
Update urllib to v2.0.7
> Update 7 modules, restricting OCCT to <7.8.0

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-wxPython.yml
Update swig-4.1.1.tar.gz to 4.2.0
Update ngspice-41.tar.gz to 42
Update OpenBLAS to v0.3.26
Update numpy-1.26.2.tar.gz to 1.26.3
Update Pillow-10.1.0.tar.gz to 10.2.0
Update Pod-Parser-1.66.tar.gz to 1.67
> beta: Update 6 modules

- kicad-doc.yml
- org.kicad.KiCad.yml
Update kicad.git to 8.0.0-rc2
Update kicad-doc.git to 8.0.0-rc2
> beta: Update 2 modules (KiCad 8.0.0-rc2)

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-requests.yml
- python3-wxPython.yml
Update libgit2 to v1.7.2
Update numpy-1.26.3.tar.gz to 1.26.4
Update certifi-2023.11.17-py3-none-any.whl to 2024.2.2
Update urllib3-2.1.0-py3-none-any.whl to 2.2.0
Update po4a-0.69.tar.gz to 0.70
> beta: Update 5 modules

- kicad-doc.yml
- org.kicad.KiCad.yml
Update kicad.git to 8.0.0-rc3
Update kicad-doc.git to 8.0.0-rc3
> beta: Update 2 modules (update to KiCad 8.0.0-rc3)

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-pytest.yml
Update kicad.git to 8.0.1-rc2
Update pytest-8.1.0-py3-none-any.whl to 8.1.1
Update asciidoctor-2.0.21.gem to 2.0.22
Update kicad-doc.git to 8.0.1-rc2
> beta: Update 4 modules (KiCad v8.0.1-rc2)

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-wxPython.yml
Update libxmu.git to 1.2.1
Update kicad.git to 8.0.2-rc2
Update meson_python-0.15.0-py3-none-any.whl to 0.16.0
Update pyproject_metadata-0.7.1-py3-none-any.whl to 0.8.0
Update kicad-doc.git to 8.0.2-rc2
> beta: Update 5 modules (KiCad v8.0.2-rc2)

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-pytest.yml
- python3-requests.yml
- python3-wxPython.yml
Update libxmu.git to 1.2.1
Update boost_1_84_0.tar.gz to 1.85.0
Update kicad.git to 8.0.2
Update meson_python-0.15.0-py3-none-any.whl to 0.16.0
Update pyproject_metadata-0.7.1-py3-none-any.whl to 0.8.0
Update idna-3.6-py3-none-any.whl to 3.7
Update pluggy-1.4.0-py3-none-any.whl to 1.5.0
Update pytest-8.1.1-py3-none-any.whl to 8.2.0
Update cairocffi-1.6.1-py3-none-any.whl to 1.7.0
Update tinycss2-1.2.1-py3-none-any.whl to 1.3.0
Update kicad-doc.git to 8.0.2
> Update 11 modules (KiCad v8.0.2)

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-pytest.yml
- python3-requests.yml
Update libgit2 to v1.8.1
Update kicad.git to 8.0.3-rc1
Update requests-2.31.0-py3-none-any.whl to 2.32.2
Update pytest-8.2.0-py3-none-any.whl to 8.2.1
Update asciidoctor-2.0.22.gem to 2.0.23
Update kicad-doc.git to 8.0.3-rc1
> beta: Update 6 modules (KiCad v8.0.3-rc1)

- org.kicad.KiCad.yml
- python3-wxPython.yml
Otherwise the new version 44.2 is rejected by f-e-d-c.
> beta: ngspice: Allow dots in version pattern

- org.kicad.KiCad.yml
Background: see https://github.com/flathub/org.kicad.KiCad/pull/369#issuecomment-2673326831
> 9.0.0 release: Change temp directory to /var/tmp, disable access to host /tmp

- kicad-doc.yml
- org.kicad.KiCad.yml
- python3-pytest.yml
- python3-requests.yml
- python3-wxPython.yml
kicad: Update kicad.git to 9.0.3-rc1
python3-requests: Update certifi-2025.4.26-py3-none-any.whl to 2025.6.15
python3-requests: Update requests-2.32.3-py3-none-any.whl to 2.32.4
python3-requests: Update urllib3-2.4.0-py3-none-any.whl to 2.5.0
openblas: Update OpenBLAS to v0.3.30
python3-numpy: Update numpy-2.3.0.tar.gz to 2.3.1
python3-pillow: Update pillow-11.2.1.tar.gz to 11.3.0
python3-pytest: Update pytest-8.4.0-py3-none-any.whl to 8.4.1
kicad-doc: Update kicad-doc.git to 9.0.3-rc1
> beta: kicad 9.0.3-rc1, Update python3-requests, openblas and 4 more modules
