org.kicad.KiCad.yml
See: https://github.com/flathub/flathub/pull/2059#discussion_r559367867
=> Change extensions versioning to `stable`

python3-wxPython.yml
=> Update numpy and Pillow

org.kicad.KiCad.yml, rename-icons-mime-and-desktop-files-for-flatpak.patch
This is needed for these resources to be exported to the host.
=> Rename icons, mime, and desktop files for flatpak

org.kicad.KiCad.yml
=> Bring back offline documentation

org.kicad.KiCad.yml
See https://gitlab.com/kicad/code/kicad/-/issues/11161
=> Force non-EGL canvas

org.kicad.KiCad.yml
Still missing:
* wxWidgets
* ngspice
=> Switch external-data-checking away from anitya

org.kicad.KiCad.yml, patches/0001_wxWidgets_Replace-gtk_combo_box_text_insert_text-with-direct-model-insertion.patch
See: https://github.com/wxWidgets/wxWidgets/pull/23443
Fixes: #156
=> Patch wxWidgets to speed up font chooser comboboxes

org.kicad.KiCad.yml
Also update Kicad docs to v7.0.3
=> Add x-checker-data info for KiCad docs

org.kicad.KiCad.yml
Update OCCT to 7_7_2
Update boost_1_82_0.tar.gz to 1.83.0
=> Beta: Update 2 modules

python3-requests.yml, python3-wxPython.yml
Update packaging-23.1-py3-none-any.whl to 23.2
Update charset_normalizer-3.2.0-py3-none-any.whl to 3.3.0
Update urllib3-2.0.5-py3-none-any.whl to 2.0.6
=> Update 3 modules

org.kicad.KiCad.yml, python3-requests.yml
Update kicad.git to 7.0.9-rc1
Update charset_normalizer-3.3.0-py3-none-any.whl to 3.3.1
=> beta: Update 2 modules (KiCad 7.0.9-rc1)

kicad-doc.yml, org.kicad.KiCad.yml, python3-wxPython.yml
Update swig-4.1.1.tar.gz to 4.2.0
Update OpenBLAS to v0.3.26
Update numpy-1.26.2.tar.gz to 1.26.3
Update Pillow-10.1.0.tar.gz to 10.2.0
Update Pod-Parser-1.66.tar.gz to 1.67
=> Update 5 modules

kicad-doc.yml, python3-requests.yml, python3-wxPython.yml
Update numpy-1.26.3.tar.gz to 1.26.4
Update certifi-2023.11.17-py3-none-any.whl to 2024.2.2
Update urllib3-2.1.0-py3-none-any.whl to 2.2.0
Update po4a-0.69.tar.gz to 0.70
=> Update 4 modules

kicad-doc.yml, org.kicad.KiCad.yml
Update kicad.git to 8.0.0
Update kicad-doc.git to 8.0.0
=> Update 2 modules (KiCad v8.0.0)

kicad-doc.yml, org.kicad.KiCad.yml, python3-requests.yml
Update glm to 1.0.1
Update swig-4.2.0.tar.gz to 4.2.1
Update kicad.git to 8.0.1-rc1
Update urllib3-2.2.0-py3-none-any.whl to 2.2.1
Update asciidoctor-2.0.20.gem to 2.0.21
=> beta: Update 5 modules

org.kicad.KiCad.yml, patches/wxWidgets_0001_Fix-wxCheckBox-undetermined-state-showing-as-checked-with-some-themes.patch, python3-pytest.yml, python3-wxPython.yml
See: https://gitlab.com/kicad/code/kicad/-/issues/17591#note_1845827598
Also: Bump our dependencies.
=> wxWidgets: Fix undefined checkboxes on some themes

.github/workflows/update.yml, flathub.json
This allows to also check the beta branch using
flatpak-external-data-checker.
=> Use custom workflow for f-e-d-c

kicad-doc.yml, org.kicad.KiCad.yml, python3-requests.yml, python3-wxPython.yml
=> Fix broken boost download link (x-checker-data)

org.kicad.KiCad.yml, python3-requests.yml, python3-wxPython.yml
=> beta: Fix broken boost download link (x-checker-data)

kicad-doc.yml, org.kicad.KiCad.yml, python3-pytest.yml, python3-wxPython.yml
And adjust protobuf's config-opts. Also update other dependencies:
- kicad-doc 9.0.1-rc1
- cssselect2 0.8.0
- numpy 2.2.4
- protobuf 30.1
- pyproject_metadata 0.9.1
- pytest 8.3.5
=> beta: Update to KiCad v9.0.1-rc1

org.kicad.KiCad.yml, python3-pytest.yml
Also:
* python3-pytest: Update iniconfig-2.0.0-py3-none-any.whl to 2.1.0
=> Beta: Revert temp libxmu archive download

org.kicad.KiCad.yml, python3-pytest.yml
Also:
* protobuf: Update protobuf.git to 29.4
* python3-pytest: Update iniconfig-2.0.0-py3-none-any.whl to 2.1.0
=> Revert temp libxmu archive download
